apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ./cabbage

resources:
- ./logging-secrets.yaml

namespace: kube-system

patchesJSON6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: cabbage
  path: logging-config-patch.yaml

- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: ClusterRoleBinding
    name: cabbage-reader-binding
  path: namespace-binding-config.yaml