# Copyright 2019 SolarWinds Worldwide, LLC.
# SPDX-License-Identifier: Apache-2.0

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ./rkubelog

namespace: kube-system

patchesJSON6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: rkubelog
  path: logging-config-patch.yaml

- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: ClusterRoleBinding
    name: rkubelog-reader-binding
  path: namespace-binding-config.yaml
