apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ./cabbage

namespace: kube-system

secretGenerator:
- name: logging-secret
  literals:
  - PAPERTRAIL_PROTOCOL=tcp
  - PAPERTRAIL_HOST=logsX.papertrailapp.com
  - PAPERTRAIL_PORT=XXXXX
  - LOGGLY_TOKEN=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  type: Opaque
    
generatorOptions:
  disableNameSuffixHash: true

patchesJSON6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: cabbage
  path: logging-config-patch.yaml

- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: ClusterRoleBinding
    name: cabbage-reader-binding
  path: namespace-binding-config.yaml