apiVersion: apps/v1
kind: Deployment
metadata:
  name: "rkubelog"
  namespace: "default"
  labels:
    app: rkubelog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rkubelog
  template:
    metadata:
      labels:
        kail.ignore: "true"
        app: rkubelog
    spec:
      serviceAccountName: rkubelog-sa
      containers:
      - image: quay.io/solarwinds/rkubelog
        imagePullPolicy: Always
        name: "rkubelog"
