name: Cabbage
on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - master

jobs:
  checks:
    name: Static checks
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: golangci/golangci-lint-action@v1
      with:
        version: v1.27
        args: --allow-parallel-runners --timeout 3m ./...
  build:
    name: build check
    runs-on: ubuntu-latest
    needs: [checks]
    steps:
    - name: Check out code
      uses: actions/checkout@master
      with:
        fetch-depth: 1
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ secrets.GO_VERSION }}
    - run: make build
    
