# Copyright 2019 SolarWinds Worldwide, LLC.
# SPDX-License-Identifier: Apache-2.0

name: ci
on:
  push:
    branches:
      - '*'
    paths-ignore:
      - 'README.md'
      - 'SECURITY.md'
      - 'LICENSE'
      - 'rkubelog/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - 'SECURITY.md'
      - 'LICENSE'
      - 'rkubelog/**'

jobs:
  checks:
    name: Static checks
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: golangci/golangci-lint-action@v2.3.0
      with:
        version: v1.35
        args: --allow-parallel-runners --timeout 3m ./...
  build:
    name: build check
    runs-on: ubuntu-latest
    needs: [checks]
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.7
    - run: make build
    
